Repository TeamHY2/HongikYeolgong2-iOS, pull requests merged in 2024-11, with the labels that each got.

#55 [Fix] 회원가입 중복체크 기능 재추가
  HongikYeolgong2.xcodeproj/project.pbxproj
  HongikYeolgong2/Core/AppEnviroment.swift
  HongikYeolgong2/Core/SystemEventHandler.swift
  HongikYeolgong2/Data/Repositories/Auth/AuthRepositoryImpl.swift
  HongikYeolgong2/Domain/Entities/User/UserInfo.swift
  HongikYeolgong2/Domain/Interactors/UserDataInteractor.swift
  HongikYeolgong2/Injected/AppState.swift
  HongikYeolgong2/Models/Department.swift
  HongikYeolgong2/Models/MockData/StudyRoomUsage+Mock.swift
  HongikYeolgong2/Models/MockData/WeeklyRanking+Mock.swift
  HongikYeolgong2/Models/Nickname.swift
  HongikYeolgong2/Models/WeekDay.swift
  HongikYeolgong2/Presentation/Auth/Onboarding/OnboardingView.swift
  HongikYeolgong2/Presentation/Auth/SignUp/SignUpView.swift
  HongikYeolgong2/Presentation/Auth/SignUpView.swift
  HongikYeolgong2/Presentation/Home/HomeView.swift
  HongikYeolgong2/Presentation/Root/InitialView.swift
  HongikYeolgong2/UI/Modifier/IOSBackground.swift
  HongikYeolgong2/Util/API/Endpoints/UserEndpoint.swift
  HongikYeolgong2/Util/Extensions/UIApplication+.swift
Labels: 🛠️ Fix, 🛠️ Refactor

#58 [Feature] RecordView 기록 출력 컴포넌트 구현 #57
  HongikYeolgong2.xcodeproj/project.pbxproj
  HongikYeolgong2/Presentation/Record/Component/RecordCell.swift
  HongikYeolgong2/Presentation/Record/RecordView.swift
  fastlane/Matchfile
Labels: 🔥 Feat, 🎨 UI

#61 [Feature] RecordView 데이터 연동 구현
  HongikYeolgong2.xcodeproj/project.pbxproj
  HongikYeolgong2/Core/AppEnviroment.swift
  HongikYeolgong2/Data/DTO/StudySession/StudyTimeResponseDTO.swift
  HongikYeolgong2/Data/Repositories/StudySession/StudySessionRepositoryImpl.swift
  HongikYeolgong2/Domain/Entities/Record/StudyTime.swift
  HongikYeolgong2/Domain/Interactors/StudyTimeInteractor.swift
  HongikYeolgong2/Domain/Interfaces/StudySessionRepository.swift
  HongikYeolgong2/Domain/Mapper/StudyTimeMapper.swift
  HongikYeolgong2/Injected/InteractorsContainer.swift
  HongikYeolgong2/Presentation/Record/RecordView.swift
  HongikYeolgong2/Util/API/Endpoints/WeeklyEndpoint.swift
Labels: 🔥 Feat

#64 [Fix] 서버 API 변경사항 대응
  HongikYeolgong2.xcodeproj/project.pbxproj
  HongikYeolgong2.xcodeproj/xcshareddata/xcschemes/HongikYeolgong2.xcscheme
  HongikYeolgong2/Data/DTO/Auth/SignUpResponseDTO.swift
  HongikYeolgong2/Data/DTO/Auth/TokenValidResponseDTO.swift
  HongikYeolgong2/Data/DTO/Weekly/WeekFieldResponseDTO.swift
  HongikYeolgong2/Data/Repositories/Auth/AuthRepositoryImpl.swift
  HongikYeolgong2/Data/Repositories/StudySession/StudySessionRepositoryImpl.swift
  HongikYeolgong2/Domain/Entities/WeeklyStudy/WeeklyStudyRecord.swift
  HongikYeolgong2/Domain/Interactors/RankingDataInteractor.swift
  HongikYeolgong2/Domain/Interactors/UserDataInteractor.swift
  HongikYeolgong2/Domain/Interfaces/AuthRepository.swift
  HongikYeolgong2/Domain/Interfaces/StudySessionRepository.swift
  HongikYeolgong2/Domain/Mapper/StudySessionMapper.swift
  HongikYeolgong2/GoogleService-Info.plist
  HongikYeolgong2/Injected/AppState.swift
  HongikYeolgong2/Injected/InteractorsContainer.swift
  HongikYeolgong2/Models/WeekDay.swift
  HongikYeolgong2/Presentation/Home/WeeklyStudy/WeeklyStudyCell.swift
  HongikYeolgong2/Presentation/Home/WeeklyStudy/WeeklyStudyView.swift
  HongikYeolgong2/Presentation/Ranking/RankingView.swift
  HongikYeolgong2/Presentation/Record/RecordView.swift
  HongikYeolgong2/Presentation/Root/InitialView.swift
  HongikYeolgong2/Util/API/Endpoints/TokenEndpoint.swift
  HongikYeolgong2/Util/API/Endpoints/WeeklyEndpoint.swift
  HongikYeolgong2/Util/Extensions/String+.swift
  HongikYeolgong2/Util/Extensions/URLRequest+.swift
  HongikYeolgong2/Util/Services/AuthenticationService.swift
Labels: 🛠️ Fix, 🛠️ Refactor

#69 [Feature] 열람실 이용관련 Notification 처리
  .DS_Store
  .gitignore
  HongikYeolgong2.xcodeproj/project.pbxproj
  HongikYeolgong2.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  HongikYeolgong2.xcodeproj/xcshareddata/xcschemes/HongikYeolgong2.xcscheme
  HongikYeolgong2/Core/SystemEventHandler.swift
  HongikYeolgong2/Domain/Interactors/StudySessionInteractor.swift
  HongikYeolgong2/GoogleService-Info.plist
  HongikYeolgong2/Injected/AppState.swift
  HongikYeolgong2/Models/StudyNotificationType.swift
  HongikYeolgong2/Presentation/Home/HomeView.swift
  HongikYeolgong2/Presentation/Home/StudyTimer/StudyTimerView.swift
  HongikYeolgong2/Presentation/Home/StudyTimer/TimePickerView.swift
  HongikYeolgong2/Presentation/Record/RecordView.swift
  HongikYeolgong2/Presentation/Root/InitialView.swift
  HongikYeolgong2/Presentation/Root/MainTabView.swift
  HongikYeolgong2/UI/Component/ModalView.swift
Labels: 🔥 Feat

#76 [Feature] SettingView 이름, 학부 바인딩을 구현합니다.
  .DS_Store
  HongikYeolgong2.xcodeproj/project.pbxproj
  HongikYeolgong2.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  HongikYeolgong2.xcodeproj/xcshareddata/xcschemes/HongikYeolgong2.xcscheme
  HongikYeolgong2/Data/Repositories/Auth/AuthRepositoryImpl.swift
  HongikYeolgong2/Domain/Entities/User/UserProfile.swift
  HongikYeolgong2/Domain/Interactors/UserDataInteractor+Migration.swift
  HongikYeolgong2/Domain/Interactors/UserDataInteractor.swift
  HongikYeolgong2/Domain/Interfaces/AuthRepository.swift
  HongikYeolgong2/Presentation/Record/RecordView.swift
  HongikYeolgong2/Presentation/Setting/SettingView.swift
  HongikYeolgong2/Util/API/Endpoints/UserEndpoint.swift
Labels: 🔥 Feat, 🎨 UI

#78 [Feature] 웹뷰를 구성하고 연결합니다.
  HongikYeolgong2.xcodeproj/project.pbxproj
  HongikYeolgong2.xcodeproj/xcshareddata/xcschemes/HongikYeolgong2.xcscheme
  HongikYeolgong2/Domain/Interactors/UserDataInteractor.swift
  HongikYeolgong2/Info.plist
  HongikYeolgong2/Presentation/Auth/Onboarding/OnboardingView.swift
  HongikYeolgong2/Presentation/Home/HomeView.swift
  HongikYeolgong2/Presentation/Other/WebView.swift
  HongikYeolgong2/Presentation/Ranking/RankingView.swift
  HongikYeolgong2/Presentation/Root/MainTabView.swift
  HongikYeolgong2/Presentation/Setting/SettingView.swift
  HongikYeolgong2/Resources/Assets.xcassets/Image/ic_close.imageset/Contents.json
  HongikYeolgong2/Resources/Assets.xcassets/Image/ic_close.imageset/ic_close.svg
  HongikYeolgong2/Util/Constants.swift
Labels: 🔥 Feat

#81 [FIX] 캘린더 초기 미생성 이슈
  HongikYeolgong2.xcodeproj/project.pbxproj
  HongikYeolgong2.xcodeproj/xcshareddata/xcschemes/HongikYeolgong2.xcscheme
  HongikYeolgong2/Presentation/Record/Component/CalendarView.swift
Labels: 🛠️ Fix

#86 [Fix] RecordView QA 대응
  HongikYeolgong2/Presentation/Record/Component/RecordCell.swift
Labels: 🎨 UI, 👀 QA

#84 [Feature] 애플로그인 회원탈퇴 정책 반영
  HongikYeolgong2.xcodeproj/project.pbxproj
  HongikYeolgong2.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  HongikYeolgong2/Core/AppEnviroment.swift
  HongikYeolgong2/Data/DTO/Auth/ASRevokeTokenRequestDTO.swift
  HongikYeolgong2/Data/DTO/Auth/ASTokenRequestDTO.swift
  HongikYeolgong2/Data/DTO/Auth/ASTokenResponseDTO.swift
  HongikYeolgong2/Data/Repositories/Auth/SocialLoginRepositoryImpl.swift
  HongikYeolgong2/Domain/Interactors/UserDataInteractor+Migration.swift
  HongikYeolgong2/Domain/Interactors/UserDataInteractor.swift
  HongikYeolgong2/Domain/Interfaces/SocialLoginRepository.swift
  HongikYeolgong2/Info.plist
  HongikYeolgong2/Injected/DependencyInjector.swift
  HongikYeolgong2/Injected/InteractorsContainer.swift
  HongikYeolgong2/Presentation/Auth/Onboarding/Component/AppleLoginButton.swift
  HongikYeolgong2/Presentation/Auth/Onboarding/Component/OnboardingPageView.swift
  HongikYeolgong2/Presentation/Auth/Onboarding/OnboardingView.swift
  HongikYeolgong2/Util/API/Base/NetworkService.swift
  HongikYeolgong2/Util/API/Endpoints/ASAuthEndpoint.swift
  HongikYeolgong2/Util/Constants.swift
  HongikYeolgong2/Util/Services/AppleLoginManager.swift
Labels: ⚙️ Chore, 🔥 Feat

#91 [Fix] RankingScreen QA 대응
  HongikYeolgong2.xcodeproj/project.pbxproj
  HongikYeolgong2.xcodeproj/xcshareddata/xcschemes/HongikYeolgong2.xcscheme
  HongikYeolgong2.xcodeproj/xcuserdata/seoggigwon.xcuserdatad/xcschemes/xcschememanagement.plist
  HongikYeolgong2/Domain/Interactors/StudySessionInteractor.swift
  HongikYeolgong2/Domain/Interactors/UserDataInteractor+Migration.swift
  HongikYeolgong2/Injected/AppState.swift
  HongikYeolgong2/Models/StudyNotificationType.swift
  HongikYeolgong2/Presentation/Auth/Onboarding/Component/OnboardingPageView.swift
  HongikYeolgong2/Presentation/Auth/Onboarding/OnboardingView.swift
  HongikYeolgong2/Presentation/Ranking/Component/RankingCell.swift
  HongikYeolgong2/Presentation/Record/RecordView.swift
  HongikYeolgong2/Presentation/Root/InitialView.swift
  HongikYeolgong2/Resources/Assets.xcassets/Image/shineOnboarding.imageset/Contents.json
  HongikYeolgong2/Resources/Assets.xcassets/Image/shineOnboarding.imageset/Vector@2x.png
  HongikYeolgong2/Resources/Assets.xcassets/Image/shineOnboarding.imageset/Vector@3x.png
  HongikYeolgong2/Resources/Assets.xcassets/Image/shineOnboarding.imageset/shineOnboarding.png
Labels: 🛠️ Refactor, 🎨 UI, 👀 QA

#96 [Feature] 로딩, 네트워크 에러 처리 구현
  .DS_Store
  HongikYeolgong2.xcodeproj/project.pbxproj
  HongikYeolgong2/Data/Repositories/StudySession/StudySessionRepositoryImpl.swift
  HongikYeolgong2/Domain/Interactors/StudyTimeInteractor.swift
  HongikYeolgong2/Presentation/Other/LoadingView.swift
  HongikYeolgong2/Presentation/Other/NetworkStateView.swift
  HongikYeolgong2/Presentation/Other/NetworkingErrorView.swift
  HongikYeolgong2/Presentation/Record/Component/StudyRecordView.swift
  HongikYeolgong2/Presentation/Record/RecordView.swift
  HongikYeolgong2/Resources/Assets.xcassets/Image/exclamationMark.imageset/Contents.json
  HongikYeolgong2/Resources/Assets.xcassets/Image/exclamationMark.imageset/Vector 1.png
  HongikYeolgong2/Resources/Assets.xcassets/Image/exclamationMark.imageset/Vector 2.png
  HongikYeolgong2/Resources/Assets.xcassets/Image/exclamationMark.imageset/Vector.png
  HongikYeolgong2/Util/Extensions/Publisher.swift
  HongikYeolgong2/Util/Loadable.swift
Labels: 🔥 Feat, 🎨 UI

#97 [Fix] SettingScreen 설정에 따라서 알림 on/off 기능을 추가합니다
  HongikYeolgong2.xcodeproj/project.pbxproj
  HongikYeolgong2/Core/AppEnviroment.swift
  HongikYeolgong2/Data/Repositories/Auth/AuthRepositoryImpl.swift
  HongikYeolgong2/Data/Repositories/Auth/SocialLoginRepositoryImpl.swift
  HongikYeolgong2/Data/Repositories/StudySession/StudySessionRepositoryImpl.swift
  HongikYeolgong2/Data/Repositories/Weekly/WeeklyRepositoryImpl.swift
  HongikYeolgong2/Domain/Interactors/StudySessionInteractor.swift
  HongikYeolgong2/Domain/Interactors/UserDataInteractor+Migration.swift
  HongikYeolgong2/Domain/Interactors/UserDataInteractor.swift
  HongikYeolgong2/Domain/Interactors/UserPermissionsInteractor.swift
  HongikYeolgong2/Injected/AppState.swift
  HongikYeolgong2/Models/Page.swift
  HongikYeolgong2/Presentation/Auth/Onboarding/Component/OnboardingPageView.swift
  HongikYeolgong2/Presentation/Auth/Onboarding/OnboardingView.swift
  HongikYeolgong2/Presentation/Auth/SignUp/SignUpView.swift
  HongikYeolgong2/Presentation/Other/WebView.swift
  HongikYeolgong2/Presentation/Ranking/Component/RankingCell.swift
  HongikYeolgong2/Presentation/Root/InitialView.swift
  HongikYeolgong2/Presentation/Setting/Component/MenuItem.swift
  HongikYeolgong2/Presentation/Setting/SettingView.swift
  HongikYeolgong2/Resources/Assets.xcassets/Image/rankDownSecond.imageset/Contents.json
  HongikYeolgong2/Resources/Assets.xcassets/Image/rankDownSecond.imageset/down_2nd@2x.png
  HongikYeolgong2/Resources/Assets.xcassets/Image/rankDownSecond.imageset/down_2nd@3x.png
  HongikYeolgong2/Resources/Assets.xcassets/Image/rankDownSecond.imageset/rankDownSecond.png
  HongikYeolgong2/Util/API/Base/NetworkService.swift
  HongikYeolgong2/Util/Services/AppleLoginManager.swift
Labels: 🛠️ Fix, 🛠️ Refactor, 👀 QA

#102 [Fix] 닉네임 정책변경 및 서버변경 내용 확인
  .DS_Store
  HongikYeolgong2.xcodeproj/project.pbxproj
  HongikYeolgong2/Data/Repositories/Auth/AuthRepositoryImpl.swift
  HongikYeolgong2/Domain/Interactors/UserDataInteractor+Migration.swift
  HongikYeolgong2/Models/Nickname.swift
  HongikYeolgong2/Presentation/Auth/Onboarding/OnboardingView.swift
  HongikYeolgong2/Presentation/Auth/SignUp/Component/SubmitButton.swift
  HongikYeolgong2/Presentation/Auth/SignUp/SignUpView.swift
  HongikYeolgong2/Resources/Assets.xcassets/Image/submitButtonDisable.imageset/Contents.json
  HongikYeolgong2/Resources/Assets.xcassets/Image/submitButtonDisable.imageset/Group 2382@2x.png
  HongikYeolgong2/Resources/Assets.xcassets/Image/submitButtonDisable.imageset/Group 2382@3x.png
  HongikYeolgong2/Resources/Assets.xcassets/Image/submitButtonDisable.imageset/submitButton.png
Labels: 🛠️ Fix, 👀 QA

#106 [Feat] Loadable 방식 수정, Loadable 로직 필요 view 적용
  HongikYeolgong2.xcodeproj/project.pbxproj
  HongikYeolgong2/Data/Repositories/Auth/AuthRepositoryImpl.swift
  HongikYeolgong2/Domain/Interactors/UserDataInteractor+Migration.swift
  HongikYeolgong2/Domain/Interactors/UserDataInteractor.swift
  HongikYeolgong2/Domain/Interactors/WeeklyStudyInteractor.swift
  HongikYeolgong2/Presentation/Auth/SignUp/SignUpView.swift
  HongikYeolgong2/Presentation/Home/HomeView.swift
  HongikYeolgong2/Presentation/Other/NetworkStateView.swift
  HongikYeolgong2/Presentation/Record/RecordView.swift
  HongikYeolgong2/Presentation/Root/RootView.swift
  HongikYeolgong2/Presentation/Setting/SettingView.swift
  HongikYeolgong2/Util/Extensions/Publisher.swift
  HongikYeolgong2/Util/Loadable.swift
Labels: 🛠️ Fix, 🔥 Feat

#109 [Feature] Amplitude를 적용합니다.
  HongikYeolgong2.xcodeproj/project.pbxproj
  HongikYeolgong2.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  HongikYeolgong2/Domain/Interactors/StudySessionInteractor.swift
  HongikYeolgong2/Info.plist
  HongikYeolgong2/Presentation/Home/HomeView.swift
  HongikYeolgong2/Presentation/Root/HongikYeolgong2App.swift
  HongikYeolgong2/Presentation/Root/MainTabView.swift
  HongikYeolgong2/Presentation/Setting/SettingView.swift
  HongikYeolgong2/Util/Constants.swift
Labels: ⚙️ Chore, 🔥 Feat
