Repository TeamHY2/HongikYeolgong2-iOS, pull requests merged in 2025-01, with the labels that each got.

#138 [Feature] 탭바기능 및 화면연결 TCA로 리팩토링
  .DS_Store
  HongikYeolgong2.xcodeproj/project.pbxproj
  HongikYeolgong2/HongikYeolgong2App.swift
  HongikYeolgong2/Presentation/AppFeature.swift
  HongikYeolgong2/Presentation/Login/LoginFeature.swift
  HongikYeolgong2/Presentation/Login/LoginView.swift
  HongikYeolgong2/Presentation/MainTabFeature.swift
  HongikYeolgong2/Presentation/MainTabView.swift
  HongikYeolgong2/Presentation/Ranking/RankingView.swift
  HongikYeolgong2/Presentation/Record/RecordView.swift
  HongikYeolgong2/Presentation/Setting/SettingFeature.swift
  HongikYeolgong2/Presentation/Setting/SettingView.swift
  HongikYeolgong2/SwiftUIView.swift
Labels: 🔥 Feat, 🎨 UI, TCA

#147 [Fix] 타이머가 자동종료시 비정상적인 시간이 등록되는 현상
  HongikYeolgong2/Domain/Interactors/StudySessionInteractor.swift
Labels: 🛠️ Fix

#146 [Feature] Alamofire 적용 NetworkLayer 구성
  HongikYeolgong2.xcodeproj/project.pbxproj
  HongikYeolgong2.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  HongikYeolgong2/Client/Auth/AuthClient.swift
  HongikYeolgong2/Network/API/Base/APIManager.swift
  HongikYeolgong2/Network/API/Base/APITask.swift
  HongikYeolgong2/Network/API/Base/Endpoint.swift
  HongikYeolgong2/Network/API/EndPoint/AuthEndpoint.swift
  HongikYeolgong2/Network/DTO/BaseResponse.swift
  HongikYeolgong2/Presentation/Auth/SignUp/SignUpFeature.swift
  HongikYeolgong2/Presentation/Record/RecordCell.swift
  HongikYeolgong2/Presentation/Record/RecordFeature.swift
  HongikYeolgong2/Secret.swift
  HongikYeolgong2/Util/Extensions/Data+.swift
Labels: 🔥 Feat, TCA

#148 [Feature] 프로필편집 기능추가
  .DS_Store
  HongikYeolgong2.xcodeproj/project.pbxproj
  HongikYeolgong2.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  HongikYeolgong2/Data/DTO/Auth/ProfileEditResponseDTO.swift
  HongikYeolgong2/Data/Repositories/Auth/AuthRepositoryImpl.swift
  HongikYeolgong2/Domain/Interactors/UserDataInteractor+Migration.swift
  HongikYeolgong2/Domain/Interactors/UserDataInteractor.swift
  HongikYeolgong2/Domain/Interfaces/AuthRepository.swift
  HongikYeolgong2/Models/Page.swift
  HongikYeolgong2/Presentation/Auth/Onboarding/OnboardingView.swift
  HongikYeolgong2/Presentation/Auth/SignUp/Component/SubmitButton.swift
  HongikYeolgong2/Presentation/Auth/SignUp/ProfileEditView.swift
  HongikYeolgong2/Presentation/Auth/SignUp/SignUpView.swift
  HongikYeolgong2/Presentation/Setting/SettingView.swift
  HongikYeolgong2/Resources/Assets.xcassets/Image/editButtonEnable.imageset/Contents.json
  HongikYeolgong2/Resources/Assets.xcassets/Image/editButtonEnable.imageset/Group 2382@2x.png
  HongikYeolgong2/Resources/Assets.xcassets/Image/editButtonEnable.imageset/Group 2382@3x.png
  HongikYeolgong2/Resources/Assets.xcassets/Image/editButtonEnable.imageset/editButtonEnable.png
  HongikYeolgong2/Resources/Assets.xcassets/Image/ic_profileLeft.imageset/Contents.json
  HongikYeolgong2/Resources/Assets.xcassets/Image/ic_profileLeft.imageset/ic_calendarLeft@2x.png
  HongikYeolgong2/Resources/Assets.xcassets/Image/ic_profileLeft.imageset/ic_calendarLeft@3x.png
  HongikYeolgong2/Resources/Assets.xcassets/Image/ic_profileLeft.imageset/ic_profileLeft.png
  HongikYeolgong2/UI/Modifier/SystemOverlay.swift
  HongikYeolgong2/Util/API/Endpoints/AuthEndpoint.swift
  HongikYeolgong2/Util/API/Endpoints/UserEndpoint.swift
Labels: 🔥 Feat

#150 [Fix] RankingScreen 순서 위치를 기준으로 고정
  HongikYeolgong2/Presentation/Ranking/Component/RankingCell.swift
  HongikYeolgong2/Presentation/Ranking/Component/RankingListView.swift
Labels: 🛠️ Fix, 🎨 UI

#152 [Feature] LoginView 구현 및 커스텀 폰트 세팅(UIkit)
  HongikYeolgong2/HongikYeolgong2.xcodeproj/project.pbxproj
  HongikYeolgong2/HongikYeolgong2/Data/Network/.gitkeep
  HongikYeolgong2/HongikYeolgong2/Data/Repositories/.gitkeep
  HongikYeolgong2/HongikYeolgong2/Domain/Entities/.gitkeep
  HongikYeolgong2/HongikYeolgong2/Domain/Interfaces/.gitkeep
  HongikYeolgong2/HongikYeolgong2/Domain/UseCases/.gitkeep
  HongikYeolgong2/HongikYeolgong2/Presentation/Auth/.gitkeep
  HongikYeolgong2/HongikYeolgong2/Presentation/Auth/Login/AppleLoginButton.swift
  HongikYeolgong2/HongikYeolgong2/Presentation/Auth/Login/LoginViewController.swift
  HongikYeolgong2/HongikYeolgong2/Presentation/Auth/SignUp/SignUpViewController.swift
  HongikYeolgong2/HongikYeolgong2/Presentation/Components/.gitkeep
  HongikYeolgong2/HongikYeolgong2/Presentation/Home/.gitkeep
  HongikYeolgong2/HongikYeolgong2/Presentation/Ranking/.gitkeep
  HongikYeolgong2/HongikYeolgong2/Presentation/Record/.gitkeep
  HongikYeolgong2/HongikYeolgong2/Presentation/Setting/.gitkeep
  HongikYeolgong2/HongikYeolgong2/Presentation/Utils/.gitkeep
  HongikYeolgong2/HongikYeolgong2/Resources/Font/.gitkeep
  HongikYeolgong2/HongikYeolgong2/Utils/Extensions/.gitkeep
  HongikYeolgong2/HongikYeolgong2/Utils/Extensions/UIFont+.swift
  HongikYeolgong2/HongikYeolgong2/Utils/Extensions/UIImage+.swift
  HongikYeolgong2/HongikYeolgong2/Utils/Protocols/.gitkeep
Labels: 🔥 Feat, 🎨 UI

#153 [Feature] 학과추가 및 삭제
  .DS_Store
  HongikYeolgong2.xcodeproj/project.pbxproj
  HongikYeolgong2/Domain/Interactors/RankingDataInteractor.swift
  HongikYeolgong2/Models/Department.swift
  HongikYeolgong2/Presentation/Home/HomeView.swift
  HongikYeolgong2/UI/Modifier/SystemOverlay.swift
Labels: 👀 QA
